services:
  website:
    image: ${WEBSITE_IMAGE:-website:local}
    build:
      context: .
    environment:
      SITE_APP_NAME: ${SITE_APP_NAME}
      PROFILE_MY_NAME: ${PROFILE_MY_NAME}
      PROFILE_ROLE: ${PROFILE_ROLE}
      PROFILE_CITY: ${PROFILE_CITY}
      PROFILE_REGION: ${PROFILE_REGION}
      PROFILE_COUNTRY: ${PROFILE_COUNTRY}
      PROFILE_AVAILABILITY: ${PROFILE_AVAILABILITY}
      SITE_PUBLIC_URL: ${SITE_PUBLIC_URL}
      SITE_GDOC_RESUME_ID: ${SITE_GDOC_RESUME_ID}
      RESUME_PDF_FILE_NAME: ${RESUME_PDF_FILE_NAME}
    container_name: website
    ports:
      - "127.0.0.1:5180:80"
    restart: unless-stopped